DEVICE = STM32F103x8
FLASH  = 0x08000000

USE_ST_CMSIS = true

STM32_BASE_PATH   	:= ../../libraries/STM32-base
STM32_CUBE_PATH   	:= ../../libraries/STM32-base-STM32Cube
TOOLCHAIN_PATH 		:= ~/dev/tool/iot/arm-gnu-embedded-toolchain/bin/

# Include the main makefile
include ../../libraries/STM32-base/make/common.mk




